### ISSUE TITLE
Add possibility for absolute path

### ISSUE THREAD

**Issue by martinknor** [ublaboo/image-storage#1]
something like `{imgLink //$image, '500x282', 'exact'}` or `{absImgLink}` ? return same as `{$baseUrl}{imgLink $image}`

**Comment by paveljanda** [comment]
It is in version v1.1.0, docu: http://ublaboo.paveljanda.com/image-storage/get-and-transform

Macros:
{img}
{imgLink}
n:img

New macros
{imgAbs}
{imgLinkAbs}
n:imgAbs
