### ISSUE TITLE
chybny popis registrace extension v /.docs/README.MD

### ISSUE THREAD

**Issue by Krejza9** [ublaboo/image-storage#12]
Ma byt:
Ublaboo\ImageStorage\DI\ImageStorageExtension

**Comment by f3l1x** [comment]
Ahoj. Doslo ke zmene namespace z Ublaboo na Contributte. Musime vydat novou verzi 2.0 a pak to bude odpovidat.

**Comment by paveljanda** [comment]
https://github.com/contributte/image-storage/compare/v2.0.4...v2.0.5
