### ISSUE TITLE
Verze pro Nette 3.0?

### ISSUE THREAD

**Issue by IJVo** [ublaboo/image-storage#16]
Prosím, kdy bude verze pro Nette 3.0?

**Comment by paveljanda** [comment]
Tuto knihovnu již nepoužívám, takže se do toho automaticky pouštět nebudu. Ale Pull-Requestu rád udělám review, případně poradím a můžeme vydat release. Možná se k tomu dostanu na nadcházející Contributte chatě, ale nechci nic slibovat. Každopádně PR vítáno. :)

**Comment by lukasojd** [comment]
+1
