### ISSUE TITLE
Problém s novou verzí nette/application 3.2.x

### ISSUE THREAD

**Issue by Ozzrell** [ublaboo/image-storage#46]
Chyba:
Declaration of Contributte\ImageStorage\ImageStoragePresenterTrait::createTemplate(): Nette\Application\UI\ITemplate must be compatible with Nette\Application\UI\Presenter::createTemplate(?string $class = null): Nette\Application\UI\Template

při vytváření traity v souboru ImageStoragePresenterTrait.php řádek  č.19

**Comment by PavelWeirich** [comment]
vyřešeno viz. #47 ee98d352f2636293c72bacbe32c2a67f4e397492

**Comment by Ozzrell** [comment]
Jo jsem imbecil co neumí číst chybová hlášení. Dík
