### ISSUE TITLE
Bad rewrite rule for friendly url

### ISSUE THREAD

**Issue by moneyfaker** [ublaboo/image-storage#5]
If file has two dots in filename (img.2.jpg) final URL is broken => ..data/d7/img.**100x100.fit.q100**.2.jpg instead of img.2.**100x100.fit.q100**.jpg

**Comment by moneyfaker** [comment]
Fixed by this regexp

```
# Images Storage conversion with directory suffix
RewriteCond %{QUERY_STRING} _image_storage
RewriteRule ^(\w+)/(\w+)/(\w+)/([^/]+)/(.+)\.(.+) $1/$2/$3/$5.$4.$6 [L]
```

(test result https://regex101.com/r/jA9fO1/5)

**Comment by paveljanda** [comment]
Thanks for the fix. I will put it on the web.
