### ISSUE TITLE
saveing resized images into different folder than the original images

### ISSUE THREAD

**Issue by hurycz** [ublaboo/image-storage#7]
i have original images in private path 
eq. `ROOT/assets/images...`

i call from template macro `{img images/123.jpg...}` and i want resized images generate in public path
eq. `ROOT/www/data/mages....`

original images not be access from website...

**Comment by paveljanda** [comment]
You can send a PR. :)

**Comment by lukasojd** [comment]
+1

**Comment by lukasojd** [comment]
+1 again ( other project )

**Comment by lukasojd** [comment]
Original and temp image must be separate in 2 folders

**Comment by vojtechmares** [comment]
@hurycz @lukasojd Hi Guys, if this issue is still in place, please consider sending a PR. Since 2 years had passed.

**Comment by attreid** [comment]
So is there any progress with approval?

**Comment by paveljanda** [comment]
Thanks
